import type { Metadata } from "next";
import "../styles/globals.css";
import "../styles/iconfont.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <Header />
        <main className="lg:pt-20 pt-12 w-screen overflow-x-hidden">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
